### ISSUE TITLE
"Windows" in ISPF

### ISSUE THREAD

**Issue by Martin-Zeithaml** [rbanffy/3270font#118]
Hi,

I have used this font for my version of  zowe tn3270, looks great and cool, but I am seeing this for each "window":

![image](https://user-images.githubusercontent.com/66114686/214866950-0f627626-2538-47a5-a178-b7705205f4e5.png)

With the default font for tn3270 the lines are fine:
![image](https://user-images.githubusercontent.com/66114686/214867702-e1a793cc-5e1b-48e9-8f93-6c996121a08d.png)

Any idea?
Thanks, Martin

**Comment by rbanffy** [comment]
That's interesting. Can you select and paste the character that's not
there? It looks like the vertical bar, but that bar is correctly
implemented on the font. It could be on a different code point than
the one the terminal expects.

On Thu, Jan 26, 2023 at 2:55 PM Martin Zeithaml
***@***.***> wrote:
>
> Hi,
>
> I have used this font for my version of zowe tn3270, looks great and cool, but I am seeing this for each "window":
>
> With the default font for tn3270 the lines are fine:
>
> Any idea?
> Thanks, Martin
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
Ricardo Bánffy
http://about.me/rbanffy

**Comment by Martin-Zeithaml** [comment]
It seems to be a problem of zowe tn3270, because I am using "experimental" branch of tn3270.

When I use IBM 3270 font in QWS3270 (terminal app for Windows), the frame is ok:

![image](https://user-images.githubusercontent.com/66114686/215043612-d57b1763-4268-4fe4-b6c8-a3b0b0aee9de.png)
