### ISSUE TITLE
Ubuntu's Russian layout has symbols absent from the font.

### ISSUE THREAD

**Issue by rbanffy** [rbanffy/3270font#12]
№, Ё and ъ are absent from the font.

**Comment by kilobyte** [comment]
That's just Russian.  For Ukrainian, you'd need Ґ ґ І і Ї ї.  The І і are usually rendered 100% as the Latin version, which for geometric letterforms like in 3270 is an obvious thing.

Not that I really care about Ukrainian, but there's one important reason: the best beer I've drank is an Ukrainian import, Оболонь Біле -- and disrespecting good beer is unthinkable.

**Comment by rbanffy** [comment]
Totally agreed. Reopening the issue until I add the remaining missing glyphs.

**Comment by rbanffy** [comment]
Seems to be fixed along #17
