### ISSUE TITLE
🔁 , 🔃 and 🔄 would be also useful. 💣 too. See http://unicode-table.com/en/#1F4A3

### ISSUE THREAD

**Issue by rbanffy** [rbanffy/3270font#14]

**Comment by kilobyte** [comment]
Be aware that all four of these characters are set as EastAsianWidth:W which on _most_ terminals makes them double-wide, so the font needs to match.

But it's worse: not sure if all systems have been fixed, but having both regular- and "full"-width glyphs in one font used to — or still does — mark the font as variable-width.

**Comment by rbanffy** [comment]
Fallback rendering results in more platform appropriate behavior.
