### ISSUE TITLE
Missing glyphs for the shrug emoji

### ISSUE THREAD

**Issue by rbanffy** [rbanffy/3270font#18]
As it is now, we can't express ¯\\\_(ツ)\_/¯ without relying on another font for rendering.

**Comment by kilobyte** [comment]
I'm not sure it's a good idea to implement just a single letter out of an alphabet: uses like that shrug can borrow the glyph from another font just fine in most terminals (Putty fails to do so), but it looks really ugly when viewing some text in that alphabet.

I don't know Japanese so here's an example in Polish: "Miałki Śnieg".  'ł' and 'Ś' look really jarring.

**Comment by rbanffy** [comment]
That's really horrifying. I'll address #17 first.
