### ISSUE TITLE
typographical details about ąĄęĘ and żŻ

### ISSUE THREAD

**Issue by kilobyte** [rbanffy/3270font#19]
As 3270font is supposed to emulate historical computing fonts rather than printing fonts, you might want to consider Polish specifics.  I don't know anything about specifically IBM3270 as we used rather adaptations of Soviet gear even if greatly inferior (by political decree) and smuggled microcomputers (there was an embargo, enforced far more strongly for mainframes than for personal computers).  As a small kid I happened to sit in ZETO Gdynia where mom worked (it was hard to get a place in kindergarten unless you were a member of the Party).  I thus have some memories of how displays were rigged to display Polish characters.

Especially żŻ were always rendered as ƶƵ (the middle dash usually somewhat shorter than the top and bottom lines, although this was not a hard rule).  This greatly helped to distinguish them from źŹ on fuzzy displays.  It's also a practice sometimes seen in uses other than computing where visibility is a concern.  There's more in Wikipedia articles on [Ż](https://en.wikipedia.org/wiki/%C5%BB) and [Ƶ](https://en.wikipedia.org/wiki/Z_with_stroke).

As of óśźćń ÓŚĆŃ, you reproduced the in-period rendering pretty well (quite obvious how to match 3270's aesthetics).  Ź is still missing.

Łł should be straightforward.

As for ąĄęĘ, the [ogonek](https://en.wikipedia.org/wiki/Ogonek) was usually a straight diagonal segment at 45° in the direction opposite the "typographical one": ie, / rather than a curved \\.  This goes against the modern rules (and proper typographers tend to be pretty [passionate](http://www.twardoch.com/download/polishhowto/ogonek.html) about those).  I've made a crude drawing:
![aaee](https://cloud.githubusercontent.com/assets/48801/17855203/ac6fcaa6-6877-11e6-8308-7a9fe3aa9df6.png)
(please don't trace this image, it was drawn really hastily and inaccurately).  Such a straight segment matches the style of 3270 pretty well.

**Comment by kilobyte** [comment]
I see the typographer I mentioned is around (@twardoch).  Let's ping him, as a professional he might have valuable comments to this issue.

**Comment by rbanffy** [comment]
As we deviate from reproducing historic hardware (I must confess I'm a bit torn about shorter letters to support accents the way they were originally - between being faithful or modern), I think it's fair to adopt typographical conventions and language that were not possible in the late 60's. Think of a 3270 built today, by people as aesthetically sensitive as its original designers, and with way more pixels in their hands.

**Comment by rbanffy** [comment]
ą, Ą, ę, Ę look reasonable to me. I'll close this for now, waiting for input from a typographer (ping @twardoch).
