### ISSUE TITLE
Missing glyphs for npm installation display

### ISSUE THREAD

**Issue by rbanffy** [rbanffy/3270font#21]
During install, npm uses some braille glyphs (?) to render. An example is "⠇".

**Comment by kilobyte** [comment]
Yes, that's Braiile (U+2800..U+28FF).  Some people [abuse](https://github.com/kilobyte/braillefont) this range for nefarious purposes. ☺

You probably want to ignore what the Unicode standard says and avoid rendering non-embossed dots.  Most fonts avoid so, FreeFont tried drawing them with [disastrous](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823029) [results](https://savannah.gnu.org/bugs/index.php?47809).

**Comment by rbanffy** [comment]
The next release will include the TRS-80/Teletext 2x3 mosaics. VTE and other terminals render these glyphs internally, ignoring the font completely. I'll say this is a lost cause.
