### ISSUE TITLE
Mangled tag v.1.2.21 spooks version scanners

### ISSUE THREAD

**Issue by kilobyte** [rbanffy/3270font#37]
Could you please delete the v.1.2.21 tag from the github repository?  It sorts above v1.2.22 in some version comparison schemes.

```
git tag -d v.1.2.21
git push origin :git tag -d v.1.2.21
```

I can easily adjust the watch file regexp in Debian, but there might be similar problems in other distributions, and it looks odd on your [tags page](https://github.com/rbanffy/3270font/tags).

**Comment by rbanffy** [comment]
Done.
