### ISSUE TITLE
Missing combining characters cause Mac to use fallback font for combined char that's not missing

### ISSUE THREAD

**Issue by rbanffy** [rbanffy/3270font#38]
Some of these chars are supposed to be defined already, but didn't show

![image](https://user-images.githubusercontent.com/184714/28748618-20711a1a-74b4-11e7-884e-68539dd81280.png)

**Comment by rbanffy** [comment]
Some investigation shows these are composite letter+accent as opposed to a single glyph representation.

**Comment by mettlerr** [comment]
Happens with German umlauts too on Mac, which is a bit unfortunate, as they are used quite often in German texts.

**Comment by rbanffy** [comment]
This is caused by the composing glyphs. 

The image below gives an idea of what's happening:

![image](https://user-images.githubusercontent.com/184714/94797781-868ae180-03d8-11eb-80ef-003277cb5f54.png)

**Comment by rbanffy** [comment]
Update: the issue is a bit more complicated in Linux:

Gnome Terminal:
![image](https://user-images.githubusercontent.com/184714/94798947-47f62680-03da-11eb-8e66-7658eb547926.png)

Konsole:
![image](https://user-images.githubusercontent.com/184714/94799090-825fc380-03da-11eb-9b18-c7d8c05e4fd2.png)

xterm:
![image](https://user-images.githubusercontent.com/184714/94799236-bb983380-03da-11eb-929e-3b378d53c130.png)

**Comment by rbanffy** [comment]
0ef5bf19531172:

![image](https://user-images.githubusercontent.com/184714/95667415-a7cc9a00-0b5d-11eb-9006-45be30e20277.png)

**Comment by rbanffy** [comment]
@mettlerr I believe the German umlauts, at least, are working on the latest develop branch.

**Comment by mettlerr** [comment]
Will test and give feedback.

**Comment by mettlerr** [comment]
Yupp, newest build works as expected, at least with the German umlauts! See screenshot: 
![3270_Test](https://user-images.githubusercontent.com/5363531/96666668-96239780-1392-11eb-9b6b-7d4747a55d86.png)
Thanks!
