### ISSUE TITLE
Drawing with Braille is becoming increasingly common

### ISSUE THREAD

**Issue by rbanffy** [rbanffy/3270font#39]
With libraries like https://github.com/asciimoo/drawille, the font needs to support the full Braille set: https://en.wikipedia.org/wiki/Braille_Patterns#Chart

![image](https://user-images.githubusercontent.com/184714/29460937-b9137e6c-8421-11e7-9e07-7e729a0f4579.png)

**Comment by kilobyte** [comment]
Ugh, vertical gaps on this screenshot look really nasty.  Horizontal gaps look seamless, though.

Quite a bunch of fonts (or rather, font+replacement pairs) have this problem, it'd be nice if you made sure that there are no gaps when no extra leading is used (like on all terminals).  Perfection is possible only when rendered at a real pixel height divisible by 4 and width by 2, but differences of 1 line are not noticeable in practice.  The screenshot has an extra 6-line gap you can drive a truck through (dots are rendered 10×10 pixels apart normally, 10×16 pixels between characters).

**Comment by zenbanffy** [comment]
With any luck, https://www.unicode.org/L2/L2017/17435r-terminals-prop.pdf will allow us to use proper 2x3 graphics blocks for these things. The spaced mosaic would still give this LED matrix visual, but the "smoothed" mosaics from ITU T.101 would be awesome for these charts.

**Comment by rbanffy** [comment]
With any luck, https://www.unicode.org/L2/L2017/17435r-terminals-prop.pdf will allow us to use proper 2x3 graphics blocks for these things. The spaced mosaic would still give this LED matrix visual, but the "smoothed" mosaics from ITU T.101 would be awesome for these charts.

**Comment by rbanffy** [comment]
Unicode 13 has the 2x3 mosaics from TRS-80/T.101 and 14 should add Kaypro 2x4, as well as the separated mosaics. I'm closing this.
