### ISSUE TITLE
Code ligatures

### ISSUE THREAD

**Issue by serl** [rbanffy/3270font#43]
What about adding a "Code" version of the font with programming ligatures, like [Fira Code](https://github.com/tonsky/FiraCode)?

**Comment by kilobyte** [comment]
Bad idea.  Unexpected ligatures don't work in any of mainstream terminals (not surprising — they are based on a cell-grid model).  They're better supported in some GUIs that are implemented using widgets meant for proportional fonts, with monospaced use only an afterthought, but the typical person with a fondness for 3270 tends to be near-religiously biased towards terminals, thus I have doubts adding such ligatures is worth the effort.

Even if the ligated version is shipped next to the char-cell one, it'd cause confusion and bug reports unless every mention of the font is accompanied with "this version is broken on terminals".

Another argument is, 3270's aesthetics are based on 50 years old terminals, so such ligatures may look out of place.
