### ISSUE TITLE
“ " ” all look the same

### ISSUE THREAD

**Issue by kilobyte** [rbanffy/3270font#47]
```
“ U+201C LEFT DOUBLE QUOTATION MARK
” U+201D RIGHT DOUBLE QUOTATION MARK
" U+0022 QUOTATION MARK
```
These "typographical" quotation marks are often created by various autocorrect tools, and are also taught as "proper" for people to use.  But, they do differ when passed to a shell/compiler/etc.  If the font you use is 3270, you don't see the difference, resulting in some quite unpleasant troubleshooting.

Could you please make them distinct?  You can either follow modern rules or historic 3270's aesthetic (straight lines at 45° angle) — either way would work.

**Comment by rbanffy** [comment]
Oops... Probably done in a moment of laziness. Will fix ASAP.

**Comment by rbanffy** [comment]
“ and ” still look off. I'll need to check that further.
