### ISSUE TITLE
Antialiasing degrading quality under 17px size

### ISSUE THREAD

**Issue by sshbio** [rbanffy/3270font#5]
On this picture, even if antialiasing is ativated, the font looks to be pixel-perfect as for a bitmap font: https://raw.githubusercontent.com/wiki/rbanffy/3270font/emacs.png

![2015-11-29-011404_1366x768_scrot](https://cloud.githubusercontent.com/assets/7250745/11454696/8df08d04-9636-11e5-9cf2-9f6841cb991a.png)
Here, at size 14 (`M-x set-frame-font RET` `-unknown-IBM 3270-normal-normal-normal-*-14-*-*-*-m-0-iso10646-1` on emacs), antialiasing make each line of the font blurred, respecting the position of the lines, but highly decreasing the quality.

By setting the font to 17 pixel (`M-x set-frame-font RET` `-unknown-IBM 3270-normal-normal-normal-*-17-*-*-*-m-0-iso10646-1` on emacs), the lines take exatly 1 px wide, and antialiasing only occur for the curves, which give the bitmap/pixel-perfect feeling.

![2015-11-29-011829_1366x768_scrot](https://cloud.githubusercontent.com/assets/7250745/11454700/ee73a86e-9636-11e5-9cdb-507c7742645a.png)

**Comment by rbanffy** [comment]
Must be something with the hinting. There is no reason to ignore it at 14 points.

**Comment by rbanffy** [comment]
I re-hinted the base ASCII set. Can you re-check?

**Comment by sshbio** [comment]
Yes, sure I will!

**Comment by sshbio** [comment]
I tried to compile, but an issue I also had with many more softwares (libsodium .so file not found) made it failed.  I then used the archive linked from the README.md, and here is the result: 

14px:

![2015-12-22-184116_1366x768_scrot](https://cloud.githubusercontent.com/assets/7250745/11962001/cc038da4-a8dc-11e5-8a8a-8db0bc164e0e.png)

17px:

![2015-12-22-184104_1366x768_scrot](https://cloud.githubusercontent.com/assets/7250745/11962027/ecee0e68-a8dc-11e5-837a-92eac987c0cd.png)

So I it is still the same result.

Maybe the issue is that at a lower size than 17px, the width of the strokes of the fonts are not thick enough to fill a whole pixel, and the font hinting balances it by graying the corresponding pixels.

I do not know if this was what you were trying to solve.  Let's hope we won't have to re-invent the whole hinting thing so this can work properly.

Anyway, thank you for your works on this font!

**Comment by rbanffy** [comment]
No problem.

/me scratches head...

There has to be *some* way to make the strokes 1 pixel wide below 14 points...

**Comment by sshbio** [comment]
I did not know that it was possible to control font aliasing from the font file itself.  If it is possible, I may be interesting for other (programming) fonts to include such possibilities as well.

**Comment by rbanffy** [comment]
There is, but I am not sure how that would happen. In any case, I made a couple changes to the a's and e's that seem more troublesome in your screenshots, as well as redid the hinting.

![tinyt](https://raw.githubusercontent.com/wiki/rbanffy/3270font/tiny.png)

![small](https://raw.githubusercontent.com/wiki/rbanffy/3270font/small.png)

![default](https://raw.githubusercontent.com/wiki/rbanffy/3270font/normal.png)

Can you try again?

**Comment by sshbio** [comment]
Redo the hinting... So that is a thing!

I built the font with `make`, and tried the different versions (only `Medium` and `Narrow` were available).

It looks sharper, with less blur, and maybe the different format managed the hinting differently.  It is incredible how the [sub-pixel geometry](https://en.wikipedia.org/wiki/Subpixel_rendering) made this following image looks very nice!
![2016-01-28-195721_1366x768_scrot](https://cloud.githubusercontent.com/assets/7250745/12655501/87770348-c5f9-11e5-96e9-d70dd645a15b.png)


I used the `.ttf` version this far, and maybe the other format manages the hinting differently.

I could have closed the issue a few commits ago, and even the original font hinting was not bad!
So we have a nicely hinted retro font to enjoy!

Thank you!

**Comment by rbanffy** [comment]
I have a feeling the OTF version renders a little bit better (on my Ubuntu Wily box), but you may also try the PostScript if the platform supports (I think I may try it on my Mac). Different font formats (which amount to different font definition languages) may render differently depending which libraries you have installed and which libraries those libraries were built against. I'm closing this for now. Let me know if the font starts acting up again.
