### ISSUE TITLE
Narrow version: last character is cut

### ISSUE THREAD

**Issue by serl** [rbanffy/3270font#6]
Hello! I like this font, so I'm using it everywhere.
I'm experiencing a little (as big as a pixel) problem: it looks like the last character is cut (only in the narrow version).

Here's a screenshot, where you can see that the last 0 is not complete:
![clock_ibm3270font_cut](https://cloud.githubusercontent.com/assets/2742655/12535824/8c28f91c-c290-11e5-809c-5a6294f0312f.png)
The screenshot is from i3bar populated by i3blocks, on i3wm. This same issue appear on the last character of each blocklet on the bar (as they're all rendered with 3270font).
As a workaround, increasing the width to 489 works, but it'll increase the size of everything, not only giving the extra space to the last character.

If you need, I could try to find an easy way to reproduce the bug.

**Comment by rbanffy** [comment]
I am not sure how, but I need to integrate sample rendering into the automated tests...

**Comment by serl** [comment]
Actually, now it cuts the zero also with width 489 :(

**Comment by rbanffy** [comment]
Oh... That really shouldn't happen... I guess we should look into i3wm's code to see if their clipping rectangles are the right size. In the meantime, can you do a screenshot at both sizes?

**Comment by serl** [comment]
Latest git, SetWidth(488): ![latest_git](https://cloud.githubusercontent.com/assets/2742655/12554330/34a9c404-c37c-11e5-9988-4d9ae31d41ac.png)

SetWidth(489): ![w489](https://cloud.githubusercontent.com/assets/2742655/12554328/34a5e55a-c37c-11e5-8e12-391809fa7368.png)

SetWidth(500): ![w500](https://cloud.githubusercontent.com/assets/2742655/12554329/34a5e2b2-c37c-11e5-858e-e24c474c2211.png)

About i3wm, I didn't see this problem with other fonts.

**Comment by rbanffy** [comment]
I made all wide numbers a little narrower (6f3c5f57ca24214ecae10cbe8e742cda912251d3). I guess I'll have to install i3wm here so it's part of the manual validation ;-). Are you using the TrueType or the OpenType version?

**Comment by serl** [comment]
I got 6f3c5f5, screenshots:
SetWidth(488): ![6f3c5f5](https://cloud.githubusercontent.com/assets/2742655/12576853/e4fc44e0-c416-11e5-8172-d31affa3abcf.png)
SetWidth(489): ![6f3c5f5_489](https://cloud.githubusercontent.com/assets/2742655/12576852/e4f956f4-c416-11e5-8772-13d59f769b76.png)
SetWidth(490): ![6f3c5f5_490](https://cloud.githubusercontent.com/assets/2742655/12576851/e4f7cc8a-c416-11e5-9422-d12b6652bf1c.png)

I also noticed that the problem shows up with almost every character that touches the right edge: the antialiasing is cutted out. I included X for example, not so noticeable but it still has the problem, I saw it also on V.

I was using ttf, so I tried otf: same behavior.

If you have time/will/curiosity to try i3, [here's the youtube video](https://www.youtube.com/watch?v=j1I63wGcvU4&list=PL5ze0DjYv5DbCv9vNEzFmP6sU7ZmkGzcf) that made me migrate to it.

**Comment by rbanffy** [comment]
I think I'll add a "SemiNarrow" version with 490 units... "Works on my machine" is not a solution, but, in the absence of a decent solution, a workaround will have to suffice.

**Comment by rbanffy** [comment]
Make it 492, just to be on the safe side.

**Comment by serl** [comment]
Agree!

Thanks
