### ISSUE TITLE
Unicode13 "symbols for legacy computing"

### ISSUE THREAD

**Issue by kilobyte** [rbanffy/3270font#66]
Unicode 13 adds a new block, at [U1FB00](https://www.unicode.org/charts/PDF/U1FB00.pdf), that seems to be close to 3270font's focus.  Well, it's about 8-bit computers and teletext rather than mainframes, but it's still a good fit.

The symbols are simple geometrical shapes, and would require little work per codepoint (but there's still a lot of them).  Being the first (or one of the first) fonts to release them would get you a lot of new installs. ☺

**Comment by rbanffy** [comment]
I'm working on that. The vte folk support most of the set already, so Gnome terminal are mostly covered. Still, I really want to do this (I am in the WG that proposed it). And there is more coming - Sharp MZ, HP terminals... Lot's of fun.

**Comment by ChiefMikeK** [comment]
## Also don't forget 🙄
---
![Image](https://github.com/ChiefMikeK/feedback/raw/master/img/Arrows_for_Legacy_Computing.png)
