### ISSUE TITLE
Empty glyph BLOCK SEXTANT-24 🬉

### ISSUE THREAD

**Issue by markisch** [rbanffy/3270font#71]
U+1FB09 turns out empty (Windows 10 18363, OTF font)

![grafik](https://user-images.githubusercontent.com/34198049/79196121-bdbc0500-7e2f-11ea-8a12-006240a85a4e.png)

Thanks for the legacy computing glyphs!

**Comment by rbanffy** [comment]
Really sorry for the delay. Fixing it now and preparing a release.
