### ISSUE TITLE
Missing overlined numbers

### ISSUE THREAD

**Issue by ctrlcctrlv** [rbanffy/3270font#77]
Via this image of an IBM 3278, we can see that the overlined digits, represented in modern Unicode in e.g. maths fonts as e.g. 3&#x0305; (U+0033 U+0305) for overlined 3, have different glyphs, but these are missing in your font.

I hope you can add them. :-) The digits are shorter to accommodate the overlines, so using the box drawing characters with the existing digits is not enough.

![overlined numbers](https://user-images.githubusercontent.com/838783/99724188-19a2d800-2a68-11eb-9885-a75c34a4863d.jpg)

**Comment by rbanffy** [comment]
I'm thinking the subscript numbers, combined with the "four dots above" combining char you(?) mentioned on Twitter.

**Comment by ctrlcctrlv** [comment]
I think you should use the normal digits and use OpenType to replace them with the correct lower height versions. Happy to provide example ,fea file. And yes that's me on Twitter.

**Comment by rbanffy** [comment]
I'll need help. My Font-Fu is very weak.

**Comment by ctrlcctrlv** [comment]
I help maintain FontForge so can even submit a PR. Would you be able to provide a higher res image of all of the decreased height digits? With that I have all I need. My image is missing `8` and `9` and so I can't do it in a historically accurate way.

**Comment by mettlerr** [comment]
Does the screenshot on the end of this page help?: http://www.prycroft6.com.au/misc/3270eds.html

I think the smaller-height numbers are on the right side, lower left corner, and seem to be 'combination characters'.

**Comment by rbanffy** [comment]
Thanks. That's pretty interesting, in special because the x3270 font that was copied from an original 3278, doesn't have these short algarisms. I wonder if they were added after the poor student copied them.

![image](https://user-images.githubusercontent.com/184714/100664243-40f28280-334f-11eb-8402-12cd52dd5d82.png)

**Comment by ctrlcctrlv** [comment]
Does anyone have the ROM? I bet the font format isn't difficult.

**Comment by rbanffy** [comment]
The "IC"s in these machines are not standard. It would be a considerable effort to extract those. If that were not enough, these terminals are horrendously expensive, even when broken.

**Comment by rbanffy** [comment]
These symbols also don't seem to be part of the EBCDIC used in these terminals, which reinforces the idea it's a special symbol used to represent some status.

https://en.wikipedia.org/wiki/Code_page_293
