### ISSUE TITLE
inconsistent font names

### ISSUE THREAD

**Issue by kilobyte** [rbanffy/3270font#82]
Names for the three width variants are inconsistent:
* "3270-Regular" "IBM 3270"
* "3270Condensed" "3270 Condensed"
* "3270SemiCondensed" "3270 Semi-Condensed"

FontName has just dash vs no-dash which is cosmetic, but Family Name having a different start makes the fonts placed in different parts of font dialogs.  Usually, the two condensed variants are at the beginning, while regular somewhere in the middle.

I'd personally prefer just "3270" as the font has been long since forked from IBM version, but the other way would be ok too.  Let's have the variants together.

**Comment by rbanffy** [comment]
One of the validations in the Google Fonts suite was complaining about starting names with numbers, so that's why I added the prefix, but forgot to rename the others. This is solved in commit [45bdfa41c](https://github.com/rbanffy/3270font/commit/45bdfa41c9eb580fff54dff3cd3f1fbf3158f5ba).
