### ISSUE TITLE
BQN adding `⋈` character

### ISSUE THREAD

**Issue by mlochbaum** [rbanffy/3270font#95]
We're preparing to add a new primitive to BQN represented by the bowtie `⋈` (U+22C8, not the similar-looking U+2A1D), so it would be nice to have 3270 support for it. I can submit a PR for it if you like. Given that it's not exactly a difficult glyph I'm guessing that's more trouble than it's worth.

No other serious primitive candidates, so chances are this is the last one to be added for quite some time. Trying to get BQN to a stable state and this is the one primitive I'd been on the fence about.

**Comment by rbanffy** [comment]
The README on the develop branch points to a zip with the added symbol. Let me know if it's good.

**Comment by mlochbaum** [comment]
Yes, both the zip file and a local build work for me! It looks a little heavier than most other symbols, but not to the point where it's jarring.

**Comment by rbanffy** [comment]
Can you post a screenshot? I can adjust the weight, but I need to know the context where the symbols are used

**Comment by mlochbaum** [comment]
Sure, here's an example where it's used: code is `((1-˜0.65⌊↕3)(0.25⊸+⊸≍¨⋈≍˜¨)1∾0.5+↕2)`. It's like `≍` and `∾` in that these all put things together, so I'd aim for a similar feel to those.

![pair](https://user-images.githubusercontent.com/1320219/140646241-aa282545-81e8-4ad5-b796-f9a0a264585c.png)
